Add split method
ktorio/ktor-io pull request #11
Opened 2022-07-19 13:22 UTC by e5l

2022-07-19 14:16 UTC, whyoleg requested changes

2022-07-19 14:16 UTC, whyoleg commented on src/commonMain/kotlin/io/ktor/io/Buffer.kt
> +    public fun takeHead(index: Int = writeIndex): Buffer
TBH, I'm not sure about the naming and overall it's contract.

Now we have:
1. absolute primitive operations (get/set)
2. relative primitive operations (read/write)
3. copy bulk(array/buffer) operations (both absolute and relative)

And this `takeHead`, which DETACHES HEAD part of current buffer from 0 up to some index looks not so good...
I see, that `netty5` have the same operation called `split`

Do you have some usecases for it's usage. I have some ideas, but it's hard for now to understand if it's will be useful.
BTW, why we (and netty) do return HEAD and not TAIL as result of this operation?

P.S. without experimenting with it it's hard for me to understand what is better

2022-07-20 15:15 UTC, ptitjes commented
@e5l I don't know if this is intended (and if it is, I fail to understand why) but:

- in `ByteArrayBuffer.takeHead`, you manually create a `ByteArrayBuffer` (and pass it the same referenceCounter and pool) and in `ByteArrayBuffer.close` you recycle `this` to the pool, whereas
- in `JvmBuffer.takeHead`, you manually create a `JvmBuffer` (and pass it the same referenceCounter, pool, and this as `origin`) and in `JvmBuffer.close` you recycle the `origin` buffer (or this, if null).

Shouldn't you also pass an origin buffer in the case of `ByteArrayBuffer`? Otherwise, won't you be adding to the pool a buffer that is sharing a `ByteArray` with a buffer instance that points to the same `ByteArray`? Maybe, there is something I am missing here...)

If we should also have an `origin` in `ByteArrayBuffer`, then I agree with @whyoleg that `ReferenceCounter` could hold the pointers to the `origin` buffer and the `pool`.

2022-07-20 15:29 UTC, ptitjes commented
@e5l Maybe I said something wrong. I searched for a scenario where that would happen. What I came with is:

```
val pool = ByteArrayBufferPool()
val originBuffer = pool.borrow()
val otherBuffer = originBuffer.takeHead(64)
originBuffer.close()
otherBuffer.close()
```

However, it just happens that the `otherBuffer` will go back to the pool instead of the `originBuffer`. But `originBuffer` can never go back to the pool, so I guess this is not a problem?

2022-07-21 06:10 UTC, e5l commented on src/commonMain/kotlin/io/ktor/io/ByteArrayBuffer.kt
> +public class ByteArrayBuffer internal constructor(
let me check

2022-07-21 06:11 UTC, e5l commented on src/commonTest/kotlin/io/ktor/io/utils/LeakDetectingPool.kt
> +        val allocation = allocations.find { it.instance === instance }
Thanks, will fix

2022-07-21 06:11 UTC, e5l commented on src/commonTest/kotlin/io/ktor/io/utils/LeakDetectingPool.kt
> +    var stack: String = Exception().stackTraceToString()
The previous implementation was reusing instances, now it's not - will drop

2022-07-21 06:12 UTC, e5l commented on src/commonTest/kotlin/io/ktor/io/utils/LeakDetectingPool.kt
> +    private val allocations = mutableListOf<Allocation<ByteArrayBuffer>>()
Could you tell me if there are some libs in common?

2022-07-21 06:12 UTC, e5l commented on src/commonTest/kotlin/io/ktor/io/utils/LeakDetectingPool.kt
> +        val array = ByteArray(DEFAULT_BUFFER_SIZE)
We can, but I'm not sure why it's needed in tests

2022-07-21 06:13 UTC, e5l commented on src/jvmMain/kotlin/io/ktor/io/JvmBuffer.kt
> +    public var raw: ByteBuffer = view
and`underlying` should be private

2022-07-21 06:14 UTC, e5l commented on src/jvmMain/kotlin/io/ktor/io/JvmBuffer.kt
> +    private val origin: JvmBuffer? = null
I'm also thinking about `Disposable` like class, will experiment with that

2022-07-21 06:15 UTC, e5l commented
@ptitjes yep it should be as in JvmBuffer, will add tests and fix

2022-07-21 06:37 UTC, whyoleg commented on src/commonTest/kotlin/io/ktor/io/utils/LeakDetectingPool.kt
> +    private val allocations = mutableListOf<Allocation<ByteArrayBuffer>>()
have no idea
there is an issue to keep track on IdentityMap in youtrack: https://youtrack.jetbrains.com/issue/KT-8435/IdentityMap
But looks like we can easily implement it with single expect/actual for identity hash code (similar to what we had in old ktor-io)
Or while we still have `Allocation` object, we can just use `Set` with identity hash code in it implementation

2022-07-21 06:38 UTC, whyoleg commented on src/jvmMain/kotlin/io/ktor/io/JvmBuffer.kt
> +    private val origin: JvmBuffer? = null
I also have some idea about pooling/refcounting/cleaner API. I will try to experiment a bit with it, and will give some feedback

2022-07-26 07:59 UTC, e5l commented
Let me think a bit about different approach

2022-07-26 07:59 UTC, closed without merging